# Generated by Django 5.2.6 on 2025-09-29 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pedidoproveedor_proveedor_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto'),
        ),
    ]
