# Generated by Django 5.2.6 on 2025-10-04 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pedidodetalle_producto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pedidoproveedor',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RECIBIDO', 'Recibido'), ('CANCELADO', 'Cancelado'), ('PAGANDO', 'Pagando')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('COTIZACION', 'Cotización'), ('BORRADOR', 'Borrador'), ('PENDIENTE_PAGO', 'Pendiente de Pago'), ('PAGADA_PENDIENTE_ENTREGA', 'Pagada y Pendiente de Entrega'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='COMPLETADA', max_length=30),
        ),
        migrations.CreateModel(
            name='PagoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto abonado', max_digits=12)),
                ('metodo_pago', models.CharField(blank=True, help_text='Efectivo, Transferencia, etc.', max_length=50)),
                ('referencia', models.CharField(blank=True, help_text='Referencia o comprobante', max_length=100)),
                ('documento_soporte', models.FileField(blank=True, null=True, upload_to='pagos_proveedores/')),
                ('notas', models.TextField(blank=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.pedidoproveedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago a Proveedor',
                'verbose_name_plural': 'Pagos a Proveedores',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
