# Generated by Django 5.2.6 on 2025-10-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cliente_direccion_cliente_razon_social_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la sucursal', max_length=200, unique=True)),
                ('codigo', models.CharField(help_text='Código único de la sucursal', max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=300)),
                ('ciudad', models.CharField(default='Barranquilla', max_length=100)),
                ('departamento', models.CharField(default='Atlántico', max_length=100)),
                ('latitud', models.DecimalField(decimal_places=7, help_text='Latitud de la ubicación', max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, help_text='Longitud de la ubicación', max_digits=10)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activa', models.BooleanField(default=True, help_text='Indica si la sucursal está operativa')),
                ('es_principal', models.BooleanField(default=False, help_text='Sucursal principal por defecto')),
                ('radio_cobertura_km', models.DecimalField(decimal_places=2, default=10.0, help_text='Radio de cobertura en kilómetros', max_digits=5)),
                ('horario_apertura', models.TimeField(blank=True, null=True)),
                ('horario_cierre', models.TimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre la sucursal')),
            ],
            options={
                'verbose_name_plural': 'Sucursales',
                'ordering': ['-es_principal', 'nombre'],
            },
        ),
    ]
