# Generated by Django 5.2.6 on 2025-10-06 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('documento', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('EN_RUTA', 'En Ruta')], default='ACTIVO', max_length=20)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Repartidores',
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='direccion_entrega',
            field=models.CharField(blank=True, help_text='Dirección de entrega', max_length=300),
        ),
        migrations.AddField(
            model_name='venta',
            name='latitud_entrega',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='longitud_entrega',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='prioridad_entrega',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', help_text='Prioridad de entrega', max_length=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='requiere_domicilio',
            field=models.BooleanField(default=False, help_text='Indica si requiere entrega a domicilio'),
        ),
        migrations.CreateModel(
            name='RutaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateField()),
                ('distancia_total_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tiempo_estimado_min', models.PositiveIntegerField()),
                ('numero_paradas', models.PositiveIntegerField()),
                ('waypoints', models.JSONField(help_text='Coordenadas de los puntos de la ruta')),
                ('geometria_ruta', models.JSONField(blank=True, help_text='Geometría completa de la ruta', null=True)),
                ('estado', models.CharField(choices=[('PLANIFICADA', 'Planificada'), ('EN_CURSO', 'En Curso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PLANIFICADA', max_length=20)),
                ('repartidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas', to='core.repartidor')),
                ('sucursal_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas', to='core.sucursal')),
            ],
            options={
                'verbose_name_plural': 'Rutas de Entrega',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_entrega', models.PositiveIntegerField(help_text='Orden en la ruta (1, 2, 3...)')),
                ('tiempo_estimado_llegada', models.TimeField(blank=True, null=True)),
                ('entregado', models.BooleanField(default=False)),
                ('hora_entrega_real', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venta')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.rutaentrega')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Ruta',
                'ordering': ['orden_entrega'],
            },
        ),
    ]
