# Generated by Django 5.2.6 on 2025-10-12 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_repartidor_venta_direccion_entrega_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaEntregaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(help_text="Descripción de la entrega (ej: 'Cliente recogió 5 unidades del producto X')")),
                ('observaciones', models.TextField(blank=True, help_text="Observaciones adicionales (ej: 'Cliente firmó conforme', 'Faltó entregar Y')")),
                ('descuento_inventario_aplicado', models.BooleanField(default=False, help_text='Indica si ya se descontó el inventario por esta nota')),
                ('usuario', models.ForeignKey(help_text='Usuario que registró la entrega', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_entrega', to='core.venta')),
            ],
            options={
                'verbose_name': 'Nota de Entrega',
                'verbose_name_plural': 'Notas de Entrega',
                'ordering': ['-fecha_entrega'],
            },
        ),
        migrations.CreateModel(
            name='DetalleNotaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_entregada', models.PositiveIntegerField(help_text='Cantidad entregada en esta nota')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
                ('nota_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_entrega', to='core.notaentregaventa')),
            ],
            options={
                'verbose_name': 'Detalle de Nota de Entrega',
                'verbose_name_plural': 'Detalles de Notas de Entrega',
            },
        ),
    ]
