# Generated by Django 5.2.6 on 2025-10-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notaentregaventa_detallenotaentrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleruta',
            name='orden_carga',
            field=models.PositiveIntegerField(default=1, help_text='Orden de carga en el vehículo (LIFO)'),
        ),
        migrations.AddField(
            model_name='detalleruta',
            name='peso_productos_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='detalleruta',
            name='volumen_productos_m3',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso_kg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Peso en kilogramos', max_digits=6),
        ),
        migrations.AddField(
            model_name='producto',
            name='volumen_m3',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Volumen en metros cúbicos', max_digits=6),
        ),
        migrations.AddField(
            model_name='rutaentrega',
            name='estado_trafico',
            field=models.JSONField(blank=True, default=dict, help_text='Información de tráfico al momento de planificar'),
        ),
        migrations.AddField(
            model_name='rutaentrega',
            name='hora_fin_real',
            field=models.DateTimeField(blank=True, help_text='Hora en que finalizó la ruta', null=True),
        ),
        migrations.AddField(
            model_name='rutaentrega',
            name='hora_inicio_real',
            field=models.DateTimeField(blank=True, help_text='Hora en que inició la ruta', null=True),
        ),
        migrations.AddField(
            model_name='rutaentrega',
            name='peso_total_kg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Peso total de la carga', max_digits=8),
        ),
        migrations.AddField(
            model_name='rutaentrega',
            name='plan_cargue',
            field=models.JSONField(blank=True, default=list, help_text='Plan de cargue LIFO con orden de productos'),
        ),
        migrations.AddField(
            model_name='rutaentrega',
            name='volumen_total_m3',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Volumen total de la carga', max_digits=8),
        ),
    ]
