# Generated by Django 5.2.6 on 2025-10-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rutaentrega_instrucciones_navegacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartidor',
            name='capacidad_maxima_kg',
            field=models.DecimalField(decimal_places=2, default=1000.0, help_text='Capacidad máxima del vehículo en kilogramos (kg)', max_digits=10),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='capacidad_maxima_m3',
            field=models.DecimalField(decimal_places=3, default=5.0, help_text='Capacidad máxima del vehículo en metros cúbicos (m³)', max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='ventana_tiempo_fin',
            field=models.TimeField(blank=True, help_text='Hora límite para realizar la entrega', null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='ventana_tiempo_inicio',
            field=models.TimeField(blank=True, help_text='Hora de inicio preferida para la entrega', null=True),
        ),
    ]
